name: Bug report 🐛
description: Submit a bug report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/Giphy/giphy-js/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: Current behavior 😯
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior 🤔
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Steps to reproduce 🕹
      description: |
        Provide a link to a live example (you can use codesandbox.io) and an unambiguous set of steps to reproduce this bug.
        Include code to reproduce, if relevant (which it most likely is).
      value: |
        Steps:

        1.
        2.
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos 📹
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓
  - type: textarea
    id: platform
    attributes:
      label: Platform 🌍
      description: |
        Please let us know which Operting System, Browser and Browser version you were using when the issue occurred.
      placeholder: |
        - OS: [e.g. macOS, Windows, Linux, iOS, Android]
        - Browser: [e.g. Chrome, Safari, Firefox, React Native]
        - Version: [e.g. 91.1]
    validations:
      required: true
  - type: input
    id: giphy-js-sdk-version
    attributes:
      label: GIPHY-JS SDK version
      description: |
        Please let us know the exact version of GIPHY-JS SDK you were using when the issue occurred. Please don't just put in "latest", as this is subject to change.
      placeholder: |
        e.g. @giphy/react-components 5.0.0
    validations:
      required: true
  - type: input
    id: ts-version
    attributes:
      label: TypeScript version
      description: |
        If you are using TypeScript, please let us know the exact version of TypeScript you were using when the issue occurred.
      placeholder: |
        e.g. v4.5.0
  - type: textarea
    id: additional
    attributes:
      label: Additional context 🔦
      description: Add any other context about the problem here.
