name: CI
on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: giphy-web
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: 'yarn'
                  add-path: true
            - run: yarn install --frozen-lockfile
            - name: Build
              run: turbo build
            - name: Lint and Test
              run: turbo lint test
            - name: Cypress
              run: turbo run cy:run --record --key $CYPRESS_RECORD_KEY
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            - name: License Check
              run: turbo check-licenses
              env:
                  LICENSE_PROJECT_LOCATION: ${{ secrets.LICENSE_PROJECT_LOCATION }}
                  LICENSE_CATEGORIES_LOCATION: ${{ secrets.LICENSE_CATEGORIES_LOCATION }}
